# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
      Proverb.create(text: "Uko na kumi nikupatie mbao?")
      Proverb.create(text: "Ata ndio nilikuwa nataka kukupigia.")
      Proverb.create(text: "Huezi nisalimia, kwani tulilala pamoja?")
      Proverb.create(text: "He is a good man, the people who surround him are the ones that are bad" )
      Proverb.create(text: "More investigations are ongoing. The perpetrators will be brought to book once we are done")
      Proverb.create(text: "Niko na pesa imeshikana")
      Proverb.create(text: "Ingia Whatsapp")
      Proverb.create(text: "Na usikuje pekee yako")
      Proverb.create(text: "Hii jua ni ya mvua")
      Proverb.create(text: "Nimewacha pombe ")
      Proverb.create(text: "Tuwache ukabila so that we can focus on development programmes")
      Proverb.create(text: "Tuma na ya kutoa")
      Proverb.create(text: "Uko na charger ya pin ndogo?")
      Proverb.create(text: "Mine is just to say something small ...")
      Proverb.create(text: "Umeoga kwani unaenda wapi?")
      Proverb.create(text: "Teachers are threatening to go on strike...")
      Proverb.create(text: "I know a guy")
      Proverb.create(text: "My life is in danger")
      Proverb.create(text: "My community is being targeted")
      Proverb.create(text: "My hands are tied")
      Proverb.create(text: "Ebu cheki kama salo imeingia." )
      Proverb.create(text: "Nikishuka ntakupigia")
      Proverb.create(text: "You are now entering a corruption free zone")
      Proverb.create(text: "Ivo ndio watu wanaangukanga mtihani,unaulizwa swali unajibu vitu zako")
      Proverb.create(text: "No stone will be left unturned." )
      Proverb.create(text: "Nitapigia Uhuru kura ndio Raila asichukue")
      Proverb.create(text: "Hii kwa duka huwezi ipata")
      Proverb.create(text: "Hakuna stage ya kumi.")
      Proverb.create(text: "Usiambie msee nimekushow.")
      Proverb.create(text: "Mtaachana tu")
      Proverb.create(text: "We have alerted the relevant authorities")
      Proverb.create(text: "I have directed thorough investigations be opened into this matter")
      Proverb.create(text: "My conscience is clear")
      Proverb.create(text: "Niflash nipate number yako")
      Proverb.create(text: "Hakuna float")
      Proverb.create(text: "Wacha nkusumbue kidogo tu")
      Proverb.create(text: "Kuja tu hivi mbele nakuona")
      Proverb.create(text: "Shukeni na hii jam.")
      Proverb.create(text: "Those who know him in person know that he is a good person")
      Proverb.create(text: "Sijakula Tangu Jana" )
      Proverb.create(text: "I have 500/- mbele na nyuma")
      Proverb.create(text: "Umenitupa sana" )
      Proverb.create(text: "Forwarded as received" )
      Proverb.create(text: "Government to resettle all IDPs by..." )
      Proverb.create(text: "Uko na truecaller?... ebu niangalilie hii namba... ")
      Proverb.create(text: "Nilibuy na 2k. But kwa shop ni 5k.")
      Proverb.create(text: "Ndio nimeona missed call sahii")
      Proverb.create(text: "Simama hapo nakuona")
      Proverb.create(text: "niko na deni ya okoa jahazi" )
      Proverb.create(text: "Hauna pesa ndogo?" )
      Proverb.create(text: "Send me your CV then when something comes up I will holla")
      Proverb.create(text: "Sasa unataka kulia?" )
      Proverb.create(text: "Mwezi Iko Kwa Corner"  )
      Proverb.create(text: "Usiniwekee mifupa mingi"   )
      Proverb.create(text: "Mimi siwezi ambiwa hivo." )
      Proverb.create(text: "Ameenda na kifunguo" )
      Proverb.create(text: "Nisave jina kama nani?")
      Proverb.create(text: "Hello, nimepata missed call yako")
      Proverb.create(text: "Hii weekend sitakuwa na pesa but naona nikienda out" )
      Proverb.create(text: "Lipa tu nitakulipa sina change." )
      Proverb.create(text: "Christmas yangu iko wapi?" )
      Proverb.create(text: "Uko na ngapi hapo uongezee tushike mzinga")
      Proverb.create(text: "Next year will be my year"  )
      Proverb.create(text: "Traffic is slow but moving"   )
      Proverb.create(text: "Naeza lipa na Mpesa?" )
      Proverb.create(text: "Niko kwa jam nakam")
      Proverb.create(text: "Kuna mahali pesa zangu zimekwama" )
      Proverb.create(text: "Niguzie hao wa mbele"   )
      Proverb.create(text: "Aki Maina I am telling you men are dogs")
